### ISSUE TITLE
Install file

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos8aa5#3]
@Abellegese 
Can you help me out in this model installs file?

The test fails because `"install_yaml_check": false` 

This is the current install file:

```
python: "3.8"
commands:
    - ['pip', 'pandas', '1.3.5']
    - ['pip', 'pydantic', '2.4.0']
    - 'pip install "torch==1.13.1+cpu" --index-url https://download.pytorch.org/whl/cpu'
    - 'conda install -c dglteam dgl=2.0.0'
    - ['pip', 'dgllife', '0.2.9']
    - ['pip', 'rdkit', '2022.3.3']
    - ['pip', 'pandas-flavor', '0.2.0']
```

I thought installing via a command directly would be accepted, but I guess either the torch or the dgl installs are failing. What do you suggest as the right structure? I have adapted the dgl install but I am less sure about the torch

**Comment by Abellegese** [comment]
Okay @GemmaTuron am looking through this, will get back to you soon.

**Comment by GemmaTuron** [comment]
The installs themselves are fine, is only the test that fails @Abellegese

**Comment by Abellegese** [comment]
Okay @GemmaTuron use this structure, it works.

```yaml
python: "3.8"
commands:
    - ['pip', 'pandas', '1.3.5']
    - ['pip', 'pydantic', '2.4.0']
    - ['pip', 'torch', '1.13.1+cpu', '--index-url', 'https://download.pytorch.org/whl/cpu']
    - ['conda', 'install', '-c', 'dglteam', 'dgl=2.0.0', '-y']
    - ['pip', 'dgllife', '0.2.9']
    - ['pip', 'rdkit', '2022.3.3']
    - ['pip', 'pandas-flavor', '0.2.0']
```
Updated the conda structure.
